API Remove deprecated code
dnadesign/silverstripe-elemental pull request #1034
Opened 2023-01-16 22:07 UTC by sabina-talipova

### Description
- Legacy GraphQL classes were removed;
- Deprecated code was removed;
- Test cases / classes updated;

### Related issue
- https://github.com/silverstripe/silverstripe-framework/issues/10501

2023-01-16 22:11 UTC, sabina-talipova commented on tests/GraphQL/FakeResolveInfo.php
> +use GraphQL\Language\AST\OperationDefinitionNode;
```
use ArrayObject;
use GraphQL\Language\AST\OperationDefinitionNode;
```
Required types of parameters in ResolveInfo constructor : https://github.com/webonyx/graphql-php/blob/master/src/Type/Definition/ResolveInfo.php#L123-L132

2023-01-16 22:53 UTC, sabina-talipova commented
Broken Behat tests are related to the issue https://github.com/silverstripeltd/product-issues/issues/655

2023-01-24 23:23 UTC, emteknetnz requested changes
Merge conflict on FakeResolveInfo

Please rebase on 5 and use the version in this commit - https://github.com/silverstripe/silverstripe-elemental/commit/43dde3acd856557ef4e24b17c91f48eeae132db7#diff-445b2b99e2d2c31b3d1a34241221643396fd9134c296395559728b3f67ade3a0

2023-01-25 01:04 UTC, sabina-talipova commented
DONE

2023-01-25 03:23 UTC, emteknetnz approved these changes

2023-01-25 03:23 UTC, merged