MNT Add tests for multi-WYSIWYG config regressions
dnadesign/silverstripe-elemental pull request #1135
Opened 2024-01-23 23:20 UTC by GuySartorelli

## Description

Tests for regressions for having multiple WYSIWYG configs.
Tests are for https://github.com/silverstripe/silverstripe-admin/issues/1512 and https://github.com/silverstripe/silverstripe-elemental/issues/1120

Needs all three of the below PRs to be merged for the CI to go green:
- https://github.com/silverstripe/silverstripe-admin/pull/1653
- https://github.com/silverstripe/silverstripe-asset-admin/pull/1435
- https://github.com/silverstripe/silverstripe-cms/pull/2916

## Manual testing steps

Load up an environment with the three linked PRs included, and run the new behat test.

## Issues

- https://github.com/silverstripe/silverstripe-elemental/issues/1120

## Pull request checklist

- [x] The target branch is correct
    - See [picking the right version](https://docs.silverstripe.org/en/contributing/code/#picking-the-right-version)
- [x] All commits are relevant to the purpose of the PR (e.g. no debug statements, unrelated refactoring, or arbitrary linting)
    - Small amounts of additional linting are usually okay, but if it makes it hard to concentrate on the relevant changes, ask for the unrelated changes to be reverted, and submitted as a separate PR.
- [x] The commit messages follow our [commit message guidelines](https://docs.silverstripe.org/en/contributing/code/#commit-messages)
- [x] The PR follows our [contribution guidelines](https://docs.silverstripe.org/en/contributing/code/)
- [x] Code changes follow our [coding conventions](https://docs.silverstripe.org/en/contributing/coding_conventions/)
- [x] This change is covered with tests (or tests aren't necessary for this change)
- [ ] CI is green

2024-01-23 23:21 UTC, GuySartorelli commented on tests/Behat/Extension/UniqueHtmlEditorConfigExtension.php
> + * @extends Extension<BaseElement>
This adds no benefit but does no harm in 4.x.
In 5.x it tells your IDE what `$this->owner` and `$this->getOwner()` are.

2024-01-24 03:57 UTC, emteknetnz requested changes
Seems like this should be in admin, not elemental?

2024-01-24 04:00 UTC, GuySartorelli commented
Relies on elemental blocks - has to be in elemental.

Update: I have tried to reproduce this without elemental and haven't been able to do so.

2024-01-24 22:40 UTC, emteknetnz approved these changes

2024-01-24 22:40 UTC, emteknetnz requested changes
Code is fine, CI is red

2024-01-24 22:53 UTC, GuySartorelli commented
Rerunning CI - as per PR description it needed the others merged first before it could go green.

2024-01-25 02:35 UTC, emteknetnz approved these changes

2024-01-25 02:35 UTC, merged