Remove redundant "(displayed if checked)" text from Title field
dnadesign/silverstripe-elemental pull request #819
Opened 2020-08-04 14:13 UTC by purplespider

The visible checkbox with the text "Displayed" next to it portrays the same message, so I'd argue adding this wording to the title doesn't provide any value. In fact, I feel it adds clutter to the interface, especially as it maintains the same prominence as the field label, due to it being set in the field title, rather than as help/description text.

**Before:**

![image](https://user-images.githubusercontent.com/329880/89304047-e24d1e80-d664-11ea-8d92-1cfb92f862ae.png)

**After:**

![image](https://user-images.githubusercontent.com/329880/89304076-ec6f1d00-d664-11ea-879a-a942f557f86d.png)

2020-08-04 16:18 UTC, ScopeyNZ commented
cc @silverstripeux

This LGTM

2020-08-04 16:49 UTC, robbieaverill commented on lang/en.yml
> +    TitleLabel: 'Title'
Non-English languages will still have more context than this does. When we change English strings we usually must use a new translation key so it doesn't pollute non-English language packs. Can you please rename this? Something like `Title: 'Title'` would do

2020-08-04 22:38 UTC, clarkepaul commented
Heads up that this was an MVP and not where it was supposed to have stayed for as long. The intention was to allow users to adjust the heading size so that it can be made semantic to the other headers being used (not all content blocks use TinyMCE so they don't have the flexibility to use hierarchy).

![image](https://user-images.githubusercontent.com/555033/89351988-3f011580-d707-11ea-8e03-e7f1d6779b86.png)

![image](https://user-images.githubusercontent.com/555033/89352007-47f1e700-d707-11ea-961d-9dc000f502e9.png)

[As per designs here](https://projects.invisionapp.com/dsm/silver-stripe/silver-stripe/asset/components/5c9c207ede91234535501a35) 

Beyond this, the next part was to move the title field to the very top when the block is open, reducing the overall height of the blocks. I wasn't going to push that part until we had the heading dropdown incorporated (small steps).

2020-08-04 22:43 UTC, clarkepaul commented
I'm thinking we used that additional text when we didn't have a label on the checkbox itself. I think its redundant now too.

2020-09-04 00:49 UTC, emteknetnz commented
@purplespider This pull request hasn't had any activity for a while. Are you going to be doing further work on it to implement the feedback from robbieaverill, or would you prefer to close it now?

2020-09-04 17:33 UTC, purplespider commented
@emteknetnz Yep, I'll update the PR to use a new translation key.

2020-09-14 19:26 UTC, robbieaverill requested changes

2020-09-14 19:26 UTC, robbieaverill commented on src/Forms/TextCheckboxGroupField.php
> +            $title = _t(__CLASS__ . '.TitleLabel', 'Title');
```suggestion
            $title = _t(__CLASS__ . '.Title', 'Title');
```

2020-09-14 19:27 UTC, robbieaverill approved these changes

2020-09-14 23:32 UTC, merged